version: "2.4"
services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: "rabbitmq-ts"
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: PyekdgANDctdPgRzU8AVaRBK
      RABBITMQ_DEFAULT_USER: test-system
      RABBITMQ_DEFAULT_PASS: # Your secret password here
      RABBITMQ_DEFAULT_VHOST: test_system
      RABBITMQ_SSL_CACERTFILE: /opt/ssl/ca_certificate.pem
      RABBITMQ_SSL_CERTFILE: /opt/ssl/server/server_certificate.pem
      RABBITMQ_SSL_KEYFILE: /opt/ssl/server/server_key.pem
      RABBITMQ_SSL_VERIFY: "verify_peer"
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
      RABBITMQ_MANAGEMENT_SSL_CACERTFILE: /opt/ssl/ca_certificate.pem
      RABBITMQ_MANAGEMENT_SSL_CERTFILE: /opt/ssl/server/server_certificate.pem
      RABBITMQ_MANAGEMENT_SSL_KEYFILE: /opt/ssl/server/server_key.pem
      RABBITMQ_MANAGEMENT_SSL_VERIFY: "verify_peer"
      RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "true"
    volumes:
      - $your_ssl_folder:/opt/ssl

    restart: always

  celery:
    image: quay.io/almalinuxorg/alts-celery:latest
    build:
      dockerfile: Dockerfile.celery
      context: .
    environment:
      CELERY_CONFIG_PATH: "/celery_config.yaml"
    command: "bash -c 'source env/bin/activate && pip3 install --upgrade pip && 
      pip3 install -r celery.txt --no-cache-dir && celery
      -A alts.worker.app worker --pool=threads --concurrency=20
      --loglevel=INFO -Q docker-x86_64-0'"
    restart: on-failure
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/alts_config.yaml:/celery_config.yaml
      - $your_ssl_folder:/opt/ssl
      - ./alts:/code/alts
      - ./resources:/code/resources
      - ./tests:/code/tests
      - ./requirements/celery.txt:/code/celery.txt
    depends_on:
      - rabbitmq

  scheduler:
    image: quay.io/almalinuxorg/alts-scheduler:latest
    build:
      dockerfile: Dockerfile.scheduler
      context: .
    environment:
      CELERY_CONFIG_PATH: "/scheduler_config.yaml"
      SCHEDULER_CONFIG_PATH: "/scheduler_config.yaml"
    command: "bash -c 'source env/bin/activate && pip3 install --upgrade pip &&
      pip3 install -r scheduler.txt --no-cache-dir && uvicorn --host 0.0.0.0
      alts.scheduler.app:app --limit-concurrency 100 --backlog 1000'"
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./configs/alts_config.yaml:/scheduler_config.yaml
      - $your_ssl_folder:/opt/ssl
      - ./alts:/code/alts
      - ./resources:/code/resources
      - ./tests:/code/tests
      - ./requirements/scheduler.txt:/code/scheduler.txt
    depends_on:
      - rabbitmq
