FROM almalinux:9

RUN mkdir -p /code && dnf update -y && dnf install python39 -y && dnf clean all
RUN cd /code && python3.9 -m venv env && source env/bin/activate \
    && pip3 install -r /code/scheduler.txt && deactivate
WORKDIR /code
