services:

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: "rabbitmq-ts"
    ports:
      - "5672:5672"
      - "5671:5671"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: PyekdgANDctdPgRzU8AVaRBK
      RABBITMQ_DEFAULT_USER: test-system
      RABBITMQ_DEFAULT_PASS: # Your secret password here
      RABBITMQ_DEFAULT_VHOST: test_system
      RABBITMQ_SSL_VERIFY: "verify_peer"
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
      RABBITMQ_MANAGEMENT_SSL_VERIFY: "verify_peer"
      RABBITMQ_MANAGEMENT_SSL_FAIL_IF_NO_PEER_CERT: "true"

  celery:
    image: alts-celery:latest
    build:
      dockerfile: Dockerfile.celery
      context: .
    environment:
      CELERY_CONFIG_PATH: "/celery_config.yaml"
    command: "celery -A alts.worker.app worker -Q docker-x86_64-0
              --pool=threads --concurrency=20 --loglevel=INFO"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./configs/alts_config.yaml:/celery_config.yaml"
      - ".:/code"
    depends_on:
      - rabbitmq

  scheduler:
    image: alts-scheduler:latest
    build:
      dockerfile: Dockerfile.scheduler
      context: .
    environment:
      CELERY_CONFIG_PATH: "/scheduler_config.yaml"
      SCHEDULER_CONFIG_PATH: "/scheduler_config.yaml"
    command: "uvicorn --host 0.0.0.0 --limit-concurrency 100 --backlog 1000 alts.scheduler.app:app"
    ports:
      - "8000:8000"
    volumes:
      - "./configs/alts_config.yaml:/scheduler_config.yaml"
      - ".:/code"
    depends_on:
      - rabbitmq

  tests:
    extends: scheduler
    environment:
      CELERY_CONFIG_PATH: "tests/tests_config.yaml"
      SCHEDULER_CONFIG_PATH: "tests/tests_config.yaml"
