---

- name: Install Celery
  hosts: celery
  vars:
    docker_users:
      - "{{ test_system_user }}"
  roles:
    - base
    # TODO: add role for building docker for s390x
    - geerlingguy.docker
    - docker_customization
    - role: terraform
      tags:
        - terraform
    - celery
