---
- name: Update Alpine packages
  command: apk --allow-untrusted update && apk --allow-untrusted upgrade

- name: Ensure that additional packages installed on Alpine 3.22
  ansible.builtin.shell:
    cmd: "apk --allow-untrusted add curl"
  when: (ansible_facts.distribution_version | string).startswith('3.22')

- name: Set extra packages for Alpine 3.22
  set_fact:
    extra_packages:
      - apk-tools
      - libapk2
    extra_alpine_repo: "{{ extra_alpine_repo_baseurl }}/{{ ansible_facts.distribution_version.split('.')[:2] | join('.') }}/stable"
  when: (ansible_facts.distribution_version | string).startswith('3.22')

- name: Install extra packages on Alpine 3.22
  include_tasks: alpine_extra_packages.yml
  loop: "{{ extra_packages }}"
  loop_control:
    loop_var: package_name
  when:
    - (ansible_facts.distribution_version | string).startswith('3.22')
    - extra_alpine_repo is defined

- name: Add custom APK repository to /etc/apk/repositories
  lineinfile:
    path: /etc/apk/repositories
    line: "{{ item.url }}"
    state: present
  with_items: "{{ repositories }}"
  when: repositories is defined and repositories | length > 0

- name: Update APK index cache
  command: apk --allow-untrusted update

- name: Update apk-tools package
  command: apk --allow-untrusted upgrade apk-tools

- name: Update libapk2 package for Alpine 3.22 envs
  command: apk --allow-untrusted upgrade libapk2
  when: (ansible_facts.distribution_version | string).startswith('3.22')

- name: Install required packages on Alpine
  command: apk --allow-untrusted add ansible bats python3 py3-pip ca-certificates procps file iproute2

- name: Install test tools in virtualenv (Alpine)
  pip:
    name:
      - pytest
      - pytest-testinfra
      - pytest-check
      - pytest-tap
    virtualenv: /opt/testenv
    virtualenv_command: python3 -m venv
  when: ansible_facts.os_family == 'Alpine' and pytest_is_needed | bool
  tags:
    - initial_provision
