---

- name: Check that expected_disk_size is defined
  set_fact:
    need_to_check_fs_size: "{{ expected_disk_size is defined }}"

- name: Gather hardware information (including disks)
  ansible.builtin.setup:
    filter:
      - ansible_devices
    gather_subset:
      - hardware
  when: need_to_check_fs_size

- name: Get /dev/sda2 size
  set_fact:
    resize_required: >-
      {{
        expected_disk_size !=
        ansible_devices.sda.partitions.sda2.size.split()[0] | float | round | int
      }}
  when: need_to_check_fs_size

- name: Re-read the partition table
  ansible.builtin.command:
    cmd: partprobe /dev/sda
  when: need_to_check_fs_size and resize_required

- name: Resize /dev/sda2
  ansible.builtin.command:
    cmd: resize2fs /dev/sda2
  when: need_to_check_fs_size and resize_required
