---
rabbitqm_host:
rabbitmq_port: 5672
rabbitmq_user:
rabbitmq_password:
rabbitmq_vhost:
result_backend:
s3_access_key_id:
s3_secret_access_key:
s3_bucket:
s3_base_path: 'celery_result_backend/'
s3_region:
s3_endpoint_url:
task_default_queue: 'default'
task_acks_late: true
task_track_started: true
artifacts_root_directory: 'test_system_artifacts'
worker_prefetch_multiplier: 1
