---
use_ssl: true
ssl_config:
  security_cert_store: '/etc/ssl/certs/*.crt'
  security_key: ''
  security_certificate: ''
  broker_ca_certificates: ''
  security_digest: 'sha256'
rabbitqm_host: 'rabbitmq'
rabbitmq_port: 5672
rabbitmq_ssl_port: 5671
rabbitmq_user: 'test-system'
rabbitmq_password:
rabbitmq_vhost: 'test_system'
result_backend: 's3'
s3_access_key_id:
s3_secret_access_key:
s3_bucket:
s3_base_path: 'celery_result_backend/'
s3_region:
s3_endpoint_url:
task_default_queue: 'default'
task_acks_late: true
task_track_started: true
artifacts_root_directory: 'test_system_artifacts'
worker_prefetch_multiplier: 1
testing:
working_directory:
jwt_secret:
hashing_algorithm: 'HS256'
opennebula_rpc_endpoint:
opennebula_username:
opennebula_password:
opennebula_vm_group:
opennebula_templates:
  ubuntu:
    '20.04':
      amd64:
