name: pytest
on:
  pull_request_target:
    branches:
      - "**"
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        name: Check out repository
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prepare SSH key
        run: |
          ssh-keygen -t ed25519 -f ~/.ssh/id_rsa -N ''
          cat > ~/.ssh/config <<EOF
            Host localhost
              User $USER
              HostName 127.0.0.1
          EOF
          cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
      - name: Prepare binary executors
        run: |
          sudo apt-get install bats ansible
      - name: Prepare python env
        run: |
          python -m venv env
          env/bin/python -m pip install -U pip
          env/bin/python -m pip install -r requirements/scheduler.txt
          env/bin/python -m pip install -r requirements/devel.txt
      - name: Run unit tests (pytest)
        env:
          CELERY_CONFIG_PATH: tests/tests_config.yaml
          SSH_USERNAME: runner
          SSH_PUBLIC_KEY: ~/.ssh/id_rsa.pub
          IGNORE_ENCRYPTED_KEYS: true
        run: set -o pipefail && env/bin/python -m pytest -v --cov-report term-missing:skip-covered
             --cov-report xml:/tmp/coverage.xml --junitxml=/tmp/pytest.xml
             --cov=alts tests/ | tee /tmp/pytest-coverage.txt
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        id: coverageComment
        with:
          pytest-coverage-path: /tmp/pytest-coverage.txt
          pytest-xml-coverage-path: /tmp/coverage.xml
          title: Coverage report for changed files
          badge-title: Total coverage
          hide-badge: false
          hide-report: false
          report-only-changed-files: true
          hide-comment: false
          remove-link-from-badge: false
          junitxml-path: /tmp/pytest.xml
      - name: Create the Badge
        if: ${{ github.ref == 'refs/heads/master' && steps.coverageComment.outputs.coverage }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 32596473c214f6d25557088b42ae28eb
          filename: alts-badge__main.json
          label: Test Coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: pytest
