---

- name: Install yum-utils
  ansible.builtin.dnf:
    name: yum-utils
    state: present

- name: Update all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    skip_broken: true
    nobest: true

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add "{{ test_system_user }}" user
  ansible.builtin.user:
    name: "{{ test_system_user }}"
    groups: wheel
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    state: present
